version: '3'
services:
  api:
    image: synechron-app
    build: .
    depends_on:
      - mongo
    ports:
      - '80:80'
    volumes:
      - .:/app/
  mongo:
    image: mongo
    ports:
      - '27017:27017'
