version: '3'
services:
  api:
    image: sample-express-app
    build: .
    networks:
      - backend
    ports:
      - '80:80'
    volumes:
      - .:/app/

networks:
  backend:
    driver: bridge
